/*
 * This source file was generated by the Gradle 'init' task
 */
package com.eomcs.cleancode;

public class App {
  public String getGreeting() {
    return "Welcome to Clean Code!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
  }
}
