/*
 * This source file was generated by the Gradle 'init' task
 */
package com.thehecklers.sburrestdemo;

public class SburRestDemoApplication {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new SburRestDemoApplication().getGreeting());
    }
}
